### ISSUE TITLE
`QUEUE_PORT` not present in environment of non-ephemeral DataInputs

### ISSUE THREAD

**Issue by ztaylor54** [NASA-PDS/kdp#13]
## 🐛 Describe the bug

When a DataInput is defined with `spec.ephemeral: false`, the Manager does not add `QUEUE_PORT` to the underlying deployment's environment.

## 📜 To Reproduce
Simply compare the container's `env` block in the manifests for [ephemeral (Job)](https://github.com/NASA-PDS/kdp/blob/main/operator/operator/manifests/datainput/job.yaml#L19) vs [non-ephemeral (Deployment)](https://github.com/NASA-PDS/kdp/blob/main/operator/operator/manifests/datainput/deployment.yaml#L21) DataInputs:

```yaml
env:
  - name: DATA_JSON
    value: '{data_json}'
  - name: QUEUE_HOSTNAME
    value: '{queue_hostname}'
  # not present in the non-ephemeral version:
  - name: QUEUE_PORT
    value: '{queue_port}'
  - name: QUEUE_ID
    value: '{queue_id}'
```
