### ISSUE TITLE
Job names longer than 63 characters fail silently

### ISSUE THREAD

**Issue by myche** [NASA-PDS/kdp#18]
## 🐛 Describe the bug
Submitting datainputs via:

`kubectl apply -f foo.yaml`

results in modified job names that can exceed an unexpected 63 character limit.  When this happens, the job will sit inactive without complaint.

One has to know to look at:

`kubectl get datainput <job name> -n <namespace> -o yaml`

and look for this magic:

```bash
      \\\"<job name>\\\"
      is invalid: [metadata.labels: Invalid value: \\\"m2020-datainput-ids-mars2020-edlcam-ops-calibrated-browse-ddc-datainput\\\":
      must be no more than 63 characters
```

Some of the name was extended after the data input was applied, so the expanded length was also unexpected:

```bash
echo -n m2020-datainput-ids-mars2020-edlcam-ops-calibrated-browse-ddc | wc -c
61
echo -n m2020-datainput-ids-mars2020-edlcam-ops-calibrated-browse-ddc-datainput | wc -c
71
```

## 🕵️ Expected behavior
It would be great if this error could fail loudly when `kubectrl apply` is used and logged such that the user could take action

## 🩺 Test Data / Additional context
```yaml
apiVersion: kdp.nasa-pds.github.io/v1
kind: DataInput
metadata:
  namespace: m2020-kdp
  name: m2020-datainput-ids-mars2020-edlcam-ops-calibrated-browse-ddc
spec:
  pipeline:
    id: product-validation-pipeline
  data:
    bundle_bucket: s3://<bundle-name>
    bundle_subpath: <prefix_to_sols>
    out_dir: s3://<another-bundle-name>
  image: <über-cool-image>.amazonaws.com/kdp-datainput-prefix-listing:latest
```

## 🖥 System Info
 - OS: AWS AMI
