### ISSUE TITLE
Scoped inputs for later pipeline steps

### ISSUE THREAD

**Issue by ztaylor54** [NASA-PDS/kdp#5]
## 💪 Motivation

We'd like to support scoped inputs for pipeline steps - there are times when certain data is needed halfway down a pipeline, but there is no need for it at the root or at any other intermediate node. It would be nice to be able to scope an input or data chunk to a particular node.

## 📖 Additional Details

The current implementation requires any values provided by a DataInput to be consumed / handled by the immediate next node, and only the _output_ of that node is passed to the next pipeline step. It seems reasonable to support something like the following in a DataInput:

```yaml
<...>
spec:
  data: # perhaps change to "input" or something to signify this is passed to the root node as input
    a_key: "some input for the root node"
  scoped:
    step-one:
       <data block>
    step-two:
      <data block>
  <...>
```

Where `step-one` and `step-two` are node names from the pipeline. It follows, then, that the environment of `step-one` should include the scoped inputs. There are two choices for this - extending the JSON input from the previous node (`KDP_INPUT` environment variable) or adding a new one. Both are probably fine, but I'd be interested in any input others may have.
